# Generated by Django 3.2.7 on 2021-10-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_of_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='device_of_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
