# Generated by Django 3.2.7 on 2021-11-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_devices', '0002_auto_20211128_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_device',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
