# Generated by Django 3.2.7 on 2021-12-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_devices', '0004_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
