# Generated by Django 3.2.7 on 2021-12-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_devices', '0005_alter_service_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
