# Generated by Django 3.2.7 on 2021-12-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_devices', '0007_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
