# Generated by Django 3.2.7 on 2021-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
