# Generated by Django 3.2.7 on 2021-10-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_service_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Device',
        ),
    ]
