# Generated by Django 3.2.7 on 2021-10-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_model_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='special_category',
            options={'verbose_name_plural': 'Special_categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'Sub_categories'},
        ),
    ]
